name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Start AWS CodeBuild
        run: |
          aws codebuild start-build --project-name realworld-example-staging-frontend-app-build

      - name: Wait for Build Completion
        id: build
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: realworld-example-staging-frontend-app-build
